import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'sonner'
import Header from '../components/Header'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kevin Love NEXT.JS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body id="root" className={inter.className}>
      <Toaster position="top-right"/>
      <Header/>
      {children}
    </body>
    </html>
  )
}
